name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '15 16 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag schose/splunk-appinspect:$(date +%s)
    - name: publish to docker hub
      uses: zenato/docker-action@master
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: schose/splunk-appinspect
          tag: latest
